service: notes-api-aws-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: 
            Fn::GetAtt:
              - NotesTable
              - Arn

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  addNote:
    handler: src/notes/addNote.handler
    events:
      - httpApi:
          path: /note
          method: post

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NotesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH